tools:
    php_cpd: true
    php_cs_fixer:
        enabled: true
        excluded_dirs: [app/config,app/config/*]
    php_loc: true
    php_mess_detector:
        enabled: true
        config:
            rulesets: [phpmd.xml]
    php_pdepend: true
    php_analyzer:
        enabled: true
        excluded_dirs: [app/config,app/config/*]
        doc_comment_fixes: true
    sensiolabs_security_checker: true
