tools:
    php_cpd: true
    php_cs_fixer: true
    php_loc: true
    php_mess_detector:
        enabled: true
        config:
            rulesets: [phpmd.xml]
    php_pdepend: true
    php_analyzer:
        enabled: true
        doc_comment_fixes: true
    sensiolabs_security_checker: true
